apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: jenkins
        image: naveenjoshi2687/dockerjenkinsimage:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home

          - name: dockersock
            mountPath: "/var/run/docker.sock"
        securityContext:
          privileged: true
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home

        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: File
